// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3K6ADN4laUigW-oAiCv1bwgMta3Cqfk8',
    appId: '1:235511981751:web:6d7054a45df5e2f6134f32',
    messagingSenderId: '235511981751',
    projectId: 'country-app-5dcac',
    authDomain: 'country-app-5dcac.firebaseapp.com',
    storageBucket: 'country-app-5dcac.appspot.com',
    measurementId: 'G-J2P6PXX231',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBU1PDee_0SNgE9HFWO-WOlJkbm-O2J9sI',
    appId: '1:235511981751:android:a3b0ba20a316675a134f32',
    messagingSenderId: '235511981751',
    projectId: 'country-app-5dcac',
    storageBucket: 'country-app-5dcac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNdW_uxBfrBgxKuLGguGA6FwKHn_2MroI',
    appId: '1:235511981751:ios:c720e04dd7dc928b134f32',
    messagingSenderId: '235511981751',
    projectId: 'country-app-5dcac',
    storageBucket: 'country-app-5dcac.appspot.com',
    iosBundleId: 'com.example.paisesApp',
  );
}
